server:
  port: 8182
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sinawo@%__1
  devtools:
    restart:
      poll-interval: 2s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  management:
    endpoints:
      web:
        exposure:
          include: "*"